### PR TITLE
extractFolder option for bulk extraction

### PR DESCRIPTION
**Pull request by jmeyer2k**
Added an extractFolder option which allows for bulk extraction. The .gitignore was required for me, but you don't need to commit it into the main repo.

### CODE REVIEW

**Comment by whisperity** [comment]
Then please alter your history so that the gitignore file is not in there and submit a new pull request as this would just pollute the project.
(Also, you can use `.git\info\exclude` as a local-only gitignore that will never be committed. Or just simply add modified files one-by-one by specifying their paths to `git add`.)

**Comment by jmeyer2k** [comment]
Cool, great, will do. Thanks for the info.

**Comment by jmeyer2k** [comment]
One sec, I need to figure out how to do this. Sorry, I'm a bit of a beginner with git.

**Comment by jmeyer2k** [comment]
Ok, GitHub isn't recognizing the changes in the pull request. I may need to create another one.

**Pull request closed without merging**
